# .github/workflows/collect-metrics.yml
name: PushCI Metrics

on:
  workflow_run:
    # must exactly match the `name:` of your other workflow
    workflows: "CI Dummy"
    # fire only when that workflow has fully completed
    types: [completed]

jobs:
  collect:
    # guard: only when the upstream run actually succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install prometheus_client requests

      - name: Debug workflow_run context
        run: |
          echo "Upstream workflow: ${{ github.event.workflow_run.name }}"
          echo "Upstream run ID:   ${{ github.event.workflow_run.id }}"
          echo "Conclusion:       ${{ github.event.workflow_run.conclusion }}"

      - name: Collect & push metrics
        env:
          GITHUB_TOKEN:    ${{ secrets.GIT_TOKEN }}
          GITHUB_REPO:     ${{ github.repository }}
          GITHUB_RUN_ID:   ${{ github.event.workflow_run.id }}
          PUSHGATEWAY_URL: http://pushgateway:9091
        run: python scripts/collect_ci_metrics.py
