# .github/workflows/collect-metrics.yml
name: PushCI Metrics

on:
  workflow_run:
    workflows:
      - "CI + SonarQube Analysis"    # must exactly match your other workflow’s `name:`
    types:
      - completed #this must be triggered

jobs:
  collect:
    # only run if the CI + SonarQube Analysis finished successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install prometheus_client requests

      - name: Collect & push metrics
        env:
          GITHUB_TOKEN:    ${{ secrets.GIT_TOKEN }}    # or your custom secret if you created one
          GITHUB_REPO:     ${{ github.repository }}
          GITHUB_RUN_ID:   ${{ github.event.workflow_run.id }}
          PUSHGATEWAY_URL: http://pushgateway:9091
        run: python scripts/collect_ci_metrics.py
