name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonar:
    name: SonarQube Analysis
    needs: test
    runs-on: [self-hosted, windows]
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin    # ← lower-case
          java-version: '11'

      - name: Install SonarScanner CLI
        run: |
          Invoke-WebRequest `
            -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-windows.zip" `
            -OutFile scanner.zip
          Expand-Archive scanner.zip -DestinationPath scanner

      - name: Run SonarQube analysis
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
          GITHUB_SHA:     ${{ needs.test.outputs.sha }}
        run: |
          .\scanner\sonar-scanner-*/bin\sonar-scanner.bat `
            -Dsonar.projectKey=assistant-bot `
            -Dsonar.sources=backend,frontend `
            -Dsonar.host.url=%SONAR_HOST_URL% `
            -Dsonar.login=%SONAR_TOKEN% `
            -Dsonar.python.coverage.reportPaths=backend/coverage.xml `
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info `
            -Dsonar.scm.revision=%GITHUB_SHA%
