name: CI + SonarQube Analysis

on:
  push:
    branches: [ main ]
    
  pull_request:

jobs:
  # ───────────────────────────────────────────────────────────────────────────────
  # 1) Matrix’d tests + coverage artifacts
  # ───────────────────────────────────────────────────────────────────────────────
  test:
    name: Matrix Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9","3.10","3.11"]
    outputs:
      commit_sha: ${{ steps.checkout.outputs.commit }}

    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps & coverage tools
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest
          pip install -r backend/requirements.txt

      - name: Run backend tests + coverage
        run: |
          pytest --junitxml=backend/test_results-${{ matrix.python-version }}.xml
          coverage run --source=backend -m pytest backend
          coverage xml -o backend/coverage-${{ matrix.python-version }}.xml

      - name: Upload pytest results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: backend/test_results-${{ matrix.python-version }}.xml

      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-${{ matrix.python-version }}
          path: backend/coverage-${{ matrix.python-version }}.xml

 
